"""Weight Custody Manifest (WCM) reference SDK: public API.

The open reference implementation of the WCM specification across all four
layers: build and jointly sign a manifest (builder + custodian, plus a sovereign
quorum when required) and verify it (Layer 1); attestation-gated key release with
a reference KBS (Layer 2); wipe-on-lapse runtime custody (Layer 3); and
derivative lineage (Layer 4). Also included: a transparency log, a threshold
split-key, a post-quantum signing profile, and hardware quote verification.

Pre-1.0 and tracking a pre-1.0 spec. See SPEC.md and the repo ROADMAP.
"""
from __future__ import annotations

from ._types import HashValue
from ._canonicalize import canonicalize, canonical_hash
from ._signing import (
    WCM_SIGNED_FIELDS,
    signing_pre_image,
    generate_ed25519,
    ed25519_from_private_bytes,
    ed25519_from_private_b64url,
    Ed25519KeyPair,
    Ed25519Signer,
    Ed25519Verifier,
    generate_ml_dsa65,
    ml_dsa65_from_seed_bytes,
    ml_dsa65_from_seed_b64url,
    MlDsa65KeyPair,
    MlDsa65Signer,
    MlDsa65Verifier,
    generate_hybrid,
    HybridKeyPair,
    HybridSigner,
    HybridVerifier,
)
from .models import (
    WeightCustodyManifest,
    Builder,
    ReleaseTerms,
    ReleasePolicy,
    RequiredGpuMeasurement,
    RequiredServingImage,
    AcceptedMeasurement,
    SovereignProfile,
    Custody,
    KbsImage,
    ManifestSignature,
    RightsHolder,
    DerivativePolicy,
    AssuranceTier,
    PhysicalHardening,
    TrustedTimeSource,
    MemoryFingerprintChallenge,
    Tenancy,
    KeyReleaseMode,
    ReplayProtection,
    ServingImageStatus,
    RevocationAuthority,
    CustodianType,
    SignatureRole,
    SignatureAlgorithm,
    KeyType,
    BaseConfidentiality,
    DeploymentModel,
    Provenance,
    ModelSigningProvenance,
)
from ._verify import (
    verify_manifest,
    VerificationContext,
    VerificationResult,
    SignatureResult,
)
from ._challenge import Challenge, ChallengeStore, ChallengeError
from .attestation import (
    CompositeEvidence,
    CpuQuote,
    GpuReport,
    MemoryFingerprint,
)
from .providers import (
    AttestationProvider,
    SoftwareProvider,
    AttestationUnavailableError,
)
from ._hw_providers import (
    CpuQuoteProvider,
    SevSnpProvider,
    AzureSnpVtpmProvider,
    AzureTdxVtpmProvider,
    TdxProvider,
    NvidiaCcProvider,
    HardwareCompositeProvider,
    select_provider,
    select_cpu_provider,
)
from .kbs import KeyBrokerService, ReleaseDecision, CheckResult
from .renewal import RenewalDecision, manifest_identity, evidence_identity
from ._seal import (
    generate_transport_keypair,
    seal_to_public_key,
    open_sealed,
    SealError,
)
from ._quote_verify import (
    QuoteVerifier,
    QuoteVerification,
    TrustStore,
    JsonQuoteParser,
    ParsedQuote,
    QuoteParser,
    QuoteFormatError,
    verify_cert_chain,
)
from .azure_vtpm import (
    AzureSnpVtpmVerifier,
    AzureTdxVtpmBundle,
    AzureTdxVtpmVerifier,
    unwrap_azure_tdx_vtpm_bundle,
)
from .custody import (
    EnclaveSession,
    SessionState,
    TimeFloor,
    KeyWipedError,
    ReattestationRequired,
    parse_cadence,
)
from .runtime_records import (
    RuntimeEvent,
    RuntimeRecord,
    runtime_public_key,
    sign_runtime_record,
    verify_runtime_record_chain,
)
from .memory_sweep import (
    BytearrayMemoryRange,
    ProtectedMemoryRange,
    memory_sweep_public_key,
    run_memory_sweep,
    verify_memory_sweep,
)
from .artifact_digest import (
    RECIPE_ID as ARTIFACT_DIGEST_RECIPE,
    ArtifactDigestError,
    artifact_digest,
    artifact_files,
)
from .lineage import verify_lineage, LineageResult, is_root
from .transparency import (
    TransparencyLog,
    SignedTreeHead,
    EntryType,
    make_leaf_preimage,
    verify_sth,
    verify_inclusion,
    verify_log_consistency,
)
from .threshold import split_secret, combine_shares, Share
from .snp import (
    SnpReport,
    parse_snp_report,
    verify_snp_report_signature,
    extract_snp_report_from_hcl,
    snp_signature_der,
    SnpQuoteParser,
)
from .tdx import (
    TdxQuote,
    TdxReport,
    parse_tdx_quote,
    verify_tdx_quote,
)
from .nvidia import (
    NvidiaGpuVerifier,
    GpuAttestationReport,
    GpuReportFormatError,
    parse_gpu_report,
    verify_gpu_report_signature,
    build_gpu_verifier,
    NVIDIA_NONCE_OFFSET,
)
from .provenance import (
    verify_provenance,
    model_signing_digest,
    ProvenanceResult,
)
from .schema import SCHEMA_ID, manifest_schema, schema_path
from .conformance import (
    CODES,
    LEVELS,
    Level,
    Outcome,
    SuiteReport,
    Verdict,
    evaluate,
    load_vectors,
    run_reference,
    score_results,
)

__version__ = "0.28.2"

__all__ = [
    "__version__",
    "HashValue",
    "canonicalize",
    "canonical_hash",
    "ARTIFACT_DIGEST_RECIPE",
    "ArtifactDigestError",
    "artifact_digest",
    "artifact_files",
    "WCM_SIGNED_FIELDS",
    "signing_pre_image",
    "generate_ed25519",
    "ed25519_from_private_bytes",
    "ed25519_from_private_b64url",
    "Ed25519KeyPair",
    "Ed25519Signer",
    "Ed25519Verifier",
    "generate_ml_dsa65",
    "ml_dsa65_from_seed_bytes",
    "ml_dsa65_from_seed_b64url",
    "MlDsa65KeyPair",
    "MlDsa65Signer",
    "MlDsa65Verifier",
    "generate_hybrid",
    "HybridKeyPair",
    "HybridSigner",
    "HybridVerifier",
    "WeightCustodyManifest",
    "Builder",
    "ReleaseTerms",
    "ReleasePolicy",
    "RequiredGpuMeasurement",
    "RequiredServingImage",
    "AcceptedMeasurement",
    "SovereignProfile",
    "Custody",
    "KbsImage",
    "ManifestSignature",
    "RightsHolder",
    "DerivativePolicy",
    "AssuranceTier",
    "PhysicalHardening",
    "TrustedTimeSource",
    "MemoryFingerprintChallenge",
    "Tenancy",
    "KeyReleaseMode",
    "ReplayProtection",
    "ServingImageStatus",
    "RevocationAuthority",
    "CustodianType",
    "SignatureRole",
    "SignatureAlgorithm",
    "KeyType",
    "BaseConfidentiality",
    "DeploymentModel",
    "Provenance",
    "ModelSigningProvenance",
    "verify_manifest",
    "VerificationContext",
    "VerificationResult",
    "SignatureResult",
    "Challenge",
    "ChallengeStore",
    "ChallengeError",
    "CompositeEvidence",
    "CpuQuote",
    "GpuReport",
    "MemoryFingerprint",
    "AttestationProvider",
    "SoftwareProvider",
    "AttestationUnavailableError",
    "CpuQuoteProvider",
    "SevSnpProvider",
    "AzureSnpVtpmProvider",
    "AzureTdxVtpmProvider",
    "AzureTdxVtpmVerifier",
    "AzureTdxVtpmBundle",
    "unwrap_azure_tdx_vtpm_bundle",
    "TdxProvider",
    "NvidiaCcProvider",
    "HardwareCompositeProvider",
    "select_provider",
    "select_cpu_provider",
    "KeyBrokerService",
    "ReleaseDecision",
    "RenewalDecision",
    "CheckResult",
    "manifest_identity",
    "evidence_identity",
    "generate_transport_keypair",
    "seal_to_public_key",
    "open_sealed",
    "SealError",
    "QuoteVerifier",
    "QuoteVerification",
    "TrustStore",
    "JsonQuoteParser",
    "ParsedQuote",
    "QuoteParser",
    "QuoteFormatError",
    "verify_cert_chain",
    "EnclaveSession",
    "SessionState",
    "TimeFloor",
    "KeyWipedError",
    "ReattestationRequired",
    "parse_cadence",
    "RuntimeEvent",
    "RuntimeRecord",
    "runtime_public_key",
    "sign_runtime_record",
    "verify_runtime_record_chain",
    "BytearrayMemoryRange",
    "ProtectedMemoryRange",
    "memory_sweep_public_key",
    "run_memory_sweep",
    "verify_memory_sweep",
    "verify_lineage",
    "LineageResult",
    "is_root",
    "TransparencyLog",
    "SignedTreeHead",
    "EntryType",
    "make_leaf_preimage",
    "verify_sth",
    "verify_inclusion",
    "verify_log_consistency",
    "split_secret",
    "combine_shares",
    "Share",
    "SnpReport",
    "parse_snp_report",
    "verify_snp_report_signature",
    "extract_snp_report_from_hcl",
    "snp_signature_der",
    "SnpQuoteParser",
    "TdxQuote",
    "TdxReport",
    "parse_tdx_quote",
    "verify_tdx_quote",
    "NvidiaGpuVerifier",
    "GpuAttestationReport",
    "GpuReportFormatError",
    "parse_gpu_report",
    "verify_gpu_report_signature",
    "build_gpu_verifier",
    "NVIDIA_NONCE_OFFSET",
    "verify_provenance",
    "model_signing_digest",
    "ProvenanceResult",
    "SCHEMA_ID",
    "manifest_schema",
    "schema_path",
    "CODES",
    "LEVELS",
    "Level",
    "Verdict",
    "Outcome",
    "SuiteReport",
    "evaluate",
    "load_vectors",
    "run_reference",
    "score_results",
]
